# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name': 'ostation',
    'version': '1.1',
    'category': 'ostation',
    'summary': 'GESTION DES STATIONS',
    'description': """
GESTION DES STATIONS.
    """,
    'depends': [],
    'data': [
        'security/ostation_security.xml',
        'security/ir.model.access.csv',
        'report/report_shift.xml',
        'report/report_shift_list.xml',
        'report/report_article.xml',
        'report/etat_cuve.xml',
        # 'report/sale_report_templates.xml',
        # 'report/invoice_report_templates.xml',
        # 'report/report_all_channels_sales_views.xml',
        # 'data/ir_sequence_data.xml',
        # 'data/sale_data.xml',
        # 'data/mail_data.xml',
        # 'wizard/sale_make_invoice_advance_views.xml',
        'views/ostation.xml',
        'views/params.xml',
        'wizard/etat.xml',
        'views/menu.xml',
        # 'views/mail_activity_views.xml',
        # 'views/assets.xml',
        # 'views/sale_portal_templates.xml',
        # 'views/sale_product_configurator_templates.xml',
        # 'views/sale_onboarding_views.xml',
        # 'views/res_config_settings_views.xml',
        # 'views/payment_views.xml',
        # 'views/product_attribute_views.xml',
        'report/reportshift.xml',
        'report/reportappro.xml',
        'report/0equipejour.xml',
        'report/1journalventejournaliere.xml',
        'report/2recette.xml',
        'report/3mouvementsrechargegaz.xml',
        'report/4mouvementsconsigne.xml',
        'report/5mouvementsaccessoire.xml',
        'report/6mouvementssolaire.xml',
        'report/7approvisionnement.xml',
        'report/8stock.xml',
        'report/9bon.xml',
        'report/10mouvementslubrifiant.xml',
        'report/11mvtsolaire.xml',
        'report/12global.xml',
        'report/report.xml',
    ],
    'installable': True,
    'auto_install': False
}
